project:
  type: website
  resources: 
    resources

website:
  title: "Natasha Freestone"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: background.qmd
        text: Background
      - href: resources.qmd
        text: Resources for Ex-Members
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true

editor: visual

