project:
  type: website

website:
  title: "counselling-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true

editor: visual

