project:
  type: website
  resources: 
    resources

website:
  title: "Natasha Freestone"
  drafts: 
    - background.qmd
    - resources.qmd
  # navbar:
  #   right:
  #     - href: index.qmd
  #       text: Home
  #     - href: background.qmd
  #       text: Background
  #     - href: resources.qmd
  #       text: Resources for Ex-Members

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true

editor: visual

